<div class="boost_table">
	<table>
		<tr>
			<td>Time:</td>
			<td id="clock"></td>
			<td>Hot Water Status:</td>
			<td id="hwStatus" class="status"></td>
			<td>Heating Status:</td>
			<td id="heatingStatus" class="status"></td>
			<td>Boost Water:</td>
			<td class="status"><a href="#"><img id="waterBoost" src="/images/circle_power.png" /></a></td>
			<td >Boost Heating:</td>
			<td class="status"><a href="#"><img id="heatingBoost" src="/images/circle_power.png" /></a></td>
		</tr>
	</table>
</div>