<div class="boost_table">
<table>
<tr>
	<td>Time:</td>
	<td><span id="clock"></span></td>
</tr>
<tr>
	<td>Hot Water:</td>
	<td><img id="water" src="/images/circle_red.png" /></td>
	<td class="small">Boost:</td>
	<td class="small"><img id="waterBoost" src="/images/off.png" /><br/>
		<span id="waterBoostTime"></span></td>
</tr>
<tr>
	<td>Heating:</td>
	<td><img id="heating" src="/images/circle_red.png" /></td>
	<td class="small">Boost:</td>
	<td class="small"><img id="heatingBoost" src="/images/off.png" /><br/>
		<span id="heatingBoostTime"></span></td>
</tr>
</table>
</div>