<script type="text/javascript">
    $(document).ready(function () {
        $('#tableContainer').jtable({
            title: 'Schedules',
            selecting: true, //Enable selecting
            multiselect: true, //Allow multiple selecting
            selectingCheckboxes: true, //Show checkboxes on first column
            actions: {
                listAction: '/api/schedules/list',
                createAction: '/api/schedules/add',
                updateAction: '/api/schedules/add',
                deleteAction: '/api/schedules/delete'
            },
            fields: {
                id: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                group: {
                    title: 'Group',
                    options: '/api/groups/list/display/options',
                    width: '15%',
                },
                day: {
                    title: 'Day',
                    options: '/api/days/list',
                },
                hourOn: {
                    title: 'Hour On',
                    options: { <?php for($i=0;$i<24;$i++){echo"'$i':'$i',";}?> }
                },
                minuteOn: {
                    title: 'Minute On',
                    options: { <?php for($i=0;$i<60;$i++){echo"'$i':'$i',";}?> }
                },
                hourOff: {
                    title: 'Hour Off',
                    options: { <?php for($i=0;$i<24;$i++){echo"'$i':'$i',";}?> }
                },
                minuteOff: {
                    title: 'Minute Off',
                    options: { <?php for($i=0;$i<60;$i++){echo"'$i':'$i',";}?> }
                },
                heatingOn: {
                    title: 'Heating On',
                    type: 'checkbox',
                    values: { '0': 'Off', '1': 'On' },
                },
                waterOn: {
                    title: 'Water On',
                    type: 'checkbox',
                    values: { '0': 'Off', '1': 'On' },
                },
                enabled: {
                    title: 'Enabled?',
                    type: 'checkbox',
                    values: { '0': 'No', '1': 'Yes' },
                },
            }
        });
 
        $('#tableContainer').jtable('load');

        $('#deleteAllButton').button().click(function () {
            var text = '<span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>Are you sure you want to delete the selected rows?';
        	var $dialog = $('<div></div>')
    		.html(text)
    		.dialog({
    			autoOpen: false,
    			title: 'Are you sure?',
    			close: function(ev, ui) { $(this).html(text); },
    			modal: true,
    			buttons: {
    				"Delete items": function() {
    					var $selectedRows = $('#tableContainer').jtable('selectedRows');
    		            $('#tableContainer').jtable('deleteRows', $selectedRows);
    					$( this ).dialog( "close" );
    				},
    				"Cancel": function() {
    					$( this ).dialog( "close" );
    				}
    			}
    		});
    	
    	$dialog.dialog('open');
            
        });
        
        $( "button" ).button();
    });
</script>

<?php echo $this->partial('partials/status.phtml'); ?>
<div id="tableContainer"></div>
<button id="deleteAllButton">Delete Selected Rows</button>
<?php echo $this->partial('partials/multiadd.phtml'); ?>