<?php echo $this->partial('partials/status.phtml'); ?>

<?php $this->headScript()->appendFile('/js/jquery-ui-timepicker-addon.js');?>
<script type="text/javascript">
function success(data) {
	var text = "";
	if (data.Result == "ERROR") {
		text = "Error: " + data.Message;
	} else {
		text = "Holiday times set";
	}

	var $dialog = $('<div></div>')
	.html(text)
	.dialog({
		autoOpen: false,
		title: 'Setting holiday times',
		close: function(ev, ui) { $(this).html(text); }
	});

	$dialog.dialog('open');

	$.getJSON("/api/configuration/holidaytimes/", function(json) {
		if(json.Result == "OK") {
			$('#timeString').html(json.Message);
		}
	});
};

$(document).ready(function() { 
	$( "#submit" ).button(); //style button
	
	//Create datetimepickers
	$('#holidayFrom').datetimepicker();
	$('#holidayTo').datetimepicker(); 

	//Submit click functionality
	$('#submit').click(function() {
		$.ajax({
			  type: 'POST',
			  url: "/api/configuration/holiday/",
			  data: {"from": $('#holidayFrom').datetimepicker('getDate'), 
				  "to": $('#holidayTo').datetimepicker('getDate')},
			  success: success,
			  dataType: 'json',
			});
	});

	//Accordian
	$(function() {
		$( "#holidayTimes" ).accordion({ collapsible: true, active: false });
	});
} );

</script>
<div id="holidayTimes">
	<h3><a href="#">Current Holiday Times</a></h3>
	<div id="timeString">
	From: <?php echo $this->holidayFrom ?>
	To: <?php echo $this->holidayTo ?>
	</div>
	<h3><a href="#">Set Holiday Times</a></h3>
	<div>
	<table>
		<tr>
			<td>Holiday From:</td>
			<td><input type="text" id="holidayFrom" /></td>
		</tr>
		<tr>
			<td>Holiday To:</td>
			<td><input type="text" id="holidayTo" /></td>
		</tr>
		<tr>
			<td></td>
			<td><button id="submit">Set Holiday</button></td>
		</tr>
	</table>
	</div>
</div>