<script type="text/javascript">
    $(document).ready(function () {
        $('#tableContainer').jtable({
            title: 'Schedules',
            actions: {
                listAction: '/api/schedules/list',
                createAction: '/api/schedules/add',
                updateAction: '/api/schedules/add',
                deleteAction: '/api/schedules/delete'
            },
            fields: {
                id: {
                    key: true,
                    create: false,
                    edit: false,
                    list: false
                },
                group: {
                    title: 'Group',
                    options: '/api/groups/list/display/options',
                    width: '15%',
                },
                day: {
                    title: 'Day',
                    options: '/api/days/list',
                },
                hourOn: {
                    title: 'Hour On',
                    options: { <?php for($i=0;$i<24;$i++){echo"'$i':'$i',";}?> }
                },
                minuteOn: {
                    title: 'Minute On',
                    options: { <?php for($i=0;$i<60;$i++){echo"'$i':'$i',";}?> }
                },
                hourOff: {
                    title: 'Hour Off',
                    options: { <?php for($i=0;$i<24;$i++){echo"'$i':'$i',";}?> }
                },
                minuteOff: {
                    title: 'Minute Off',
                    options: { <?php for($i=0;$i<60;$i++){echo"'$i':'$i',";}?> }
                },
                heatingOn: {
                    title: 'Heating On',
                    type: 'checkbox',
                    values: { '0': 'Off', '1': 'On' },
                },
                waterOn: {
                    title: 'Water On',
                    type: 'checkbox',
                    values: { '0': 'Off', '1': 'On' },
                },
                enabled: {
                    title: 'Enabled?',
                    type: 'checkbox',
                    values: { '0': 'No', '1': 'Yes' },
                },
            }
        });
 
        $('#tableContainer').jtable('load');
    });
</script>

<div class="boost_table">
<table>
	<tr>
		<td>Time:</td>
		<td id="clock"></td>
		<td>Hot Water Status:</td>
		<td id="hwStatus" class="status"></td>
		<td>Heating Status:</td>
		<td id="heatingStatus" class="status"></td>
		<td>Boost Water:</td>
		<td class="status"><a href="#"><img id="waterBoost" src="/images/circle_power.png" /></a></td>
		<td >Boost Heating:</td>
		<td class="status"><a href="#"><img id="heatingBoost" src="/images/circle_power.png" /></a></td>
	</tr>
</table>
</div>
<div id="tableContainer"></div>
<div id="accordion">
	<?php $this->headScript()->appendFile('/js/jquery.form.js');?>
	<?php $this->headScript()->appendFile('/js/multiAdd.js');?>
	<h3><a href="#">Add multiple days at once</a></h3>
	<div>
		<form id="multiAdd" action="/api/schedules/multiadd/">
		<p>Group: <br/>
		<select name="group">
		<?php $groups = $this->Group()->getGroups();
		foreach ($groups as $group) :?>
			<option value="<?php echo $group->id ?>"><?php echo $group->name ?></option>
		<?php endforeach; ?>
		</select>
		</p>
		<p>Days: <br/> 
		<?php $days = $this->Day()->getArray();
		foreach ($days as $value => $name) :?>
			<?php echo $name ?>: <input name="day-<?php echo $value ?>" type="checkbox" value="1" /> 
		<?php endforeach; ?>
		</p>
		<p>Hour On: <br/>
		<select name="hourOn">
		<?php for ($i = 0; $i < 24; $i++) :?>
			<option value="<?php echo $i ?>"><?php echo $i ?></option>
		<?php endfor; ?>
		</select>
		</p>
		<p>Minute On: <br/> 
		<select name="minuteOn">
		<?php for ($i = 0; $i < 60; $i++) :?>
			<option value="<?php echo $i ?>"><?php echo $i ?></option>
		<?php endfor; ?>
		</select>
		</p>
		<p>Hour Off: <br/>
		<select name="hourOff">
		<?php for ($i = 0; $i < 24; $i++) :?>
			<option value="<?php echo $i ?>"><?php echo $i ?></option>
		<?php endfor; ?>
		</select>
		</p>
		<p>Minute Off: <br/> 
		<select name="minuteOff">
		<?php for ($i = 0; $i < 60; $i++) :?>
			<option value="<?php echo $i ?>"><?php echo $i ?></option>
		<?php endfor; ?>
		</select>
		</p>
		<p>Heating On: <br/> <input name="heatingOn" type="checkbox" value="1" /></p>
		<p>Water  On: <br/> <input name="waterOn" type="checkbox" value="1" /></p>
		<p>Enabled: <br/> <input name="enabled" type="checkbox" value="1" /></p>
		<p><input type="reset" value="Reset" />
		<input type="submit" value="Save" /></p>
		
		</form>
	</div>
</div>